language: android

node_js:
  - 7.7

notifications:
  email: false

sudo: false

branches:
  only:
  - test/travis

install:
  - npm install -g cordova
  - npm install -g ionic
  - npm install
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - ionic platform rm android
  - ionic platform add android

script:
  - ionic build android --release -- --ant
  
release:
  - exit 0
