language: android

node_js:
  - "7"

notifications:
  email: false

sudo: required

branches:
  only:
  - test/travis

install:
  - sudo npm install -g n
  - sudo n stable
  - sudo npm install -g npm
  - sudo npm install -g cordova
  - sudo npm install -g ionic
  - sudo npm install
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - ionic platform rm android
  - ionic platform add android

script:
  - ionic build android --release -- --ant
  
release:
  - exit 0
