
sudo: required

language: node_js
node_js:
  - "7"
env:
  CXX=g++-4.8

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

before_script:
  - sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get --assume-yes install oracle-java8-installer
  - sudo apt-get --assume-yes install oracle-java8-set-default
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
script:
  - mkdir www
  - ionic platform add android
  - ionic build android --prod -aot
  - ls -la
deploy:
  provider: releases
  api_key:
    secure: bOzcigW/XWUPGmEJyM2cfe3GGkJyrTr8pQpiyyFkFSAUjb1VEl7T2pvOcOwnooURDXyxI5tk8XRtT+fEYMrESvUUY+OXg69wzkzBfXL184tYGujS222blV/XlYlP1qgErCQ71bLI0KoSYXV9pQ/lT8+DEd7l9n/lRMUaOk0mGOarGzZwYmP9NN0rrQyw2qDxLdw6zdzsskDM6ejIN1Hd5gP0MF8hNGn96zO/V6uFpcl992F5Ir3pcryJ5Ya2Y+OniPNEGKKO8XDeNCF+oo+6tHOzM5JE5cC70tc88cIrQrIjO7sgqo3sgVL0pM8CUTQjWLR0aCe7XEQMj3iGaTtFbIteHGLHVfioqJ9Fo859NR035mQlX63OK7iFMAzQKWWfXViTtoK200d1Rbn4+eyj+S6mboma3e3HctRSEwU0xM9wCUhBWj+wvjuypPOjU+VmO8zlxrXfikN4iOz9OfDnypFuyQG7gXiY5+wx8OJRVza4HVNlEnL4ARNO4uRrx9mxvKleEEDlea/eNThPmyCbCuVK9jzKoyZdSglwQ4Cb5ouOO72XkFg0AVQRtXVAUHbNh87Wum2qTrM0FDveZFvc4qLLxZzGU1A0OYei9Z3Ym4LSb8gOGoicskM4TxcZv9L/Op2ivB1i/BQPPOu58gd3FYSvg0ljDePVlDxyvrfawoU=
  file: "platforms/android/build/outputs/apk/android-debug.apk"
  on:
    repo: KanaoReeves/KeanuFromFront
    branch: test/travis
